Introduce to start or stop gameserver remotly via webho…
jammsen/docker-palworld-dedicated-server pull request #174
Opened 2024-02-03 23:55 UTC by masonen

## Summary

This PR introduces the possiblity to controll the gameserver status (start & stop the server) via a webhook

## Motivation

Currently the dedicated servers still face a bug where pals are loosing sanity or starve when no player is connected and they get stuck. A current workaround is to stop the server while no one is active. While this bug is of course not in scope of this project i still consider the changes valuable to the project.

Since my servers are used by a small defined group of people which dont have direct CLI access to my host machines (and should not get it) an _incomming_ webhook is a good solution to allow them to controll the serverstatus. Its not in the scope of this project. The hoster can decide on how to make this webhooks availiable to the users/admins of the servers. In my case im currently building a discord bot to access the webhooks securely inside my network without publicly exposing the webhooks, other usecases might include direct web access, web integrations and many more (up to the server maintainer.

## Changes included

- rework of servermanager to handle the spawn of the webhook if envvar is set. Extract all other functionalities regarding server handling or termination handling to own script
- introduction of remotestart and remote stop script which is used by the webhook
- introduction of new webhook outputs related to the remote controll webhooks
- introduce a build layer to the dockerfile that builds the webhook binary from source (https://github.com/adnanh/webhook)
- small fixesin default.env (spaces only allowed inside quotes), fixes in envvars of docker file

2024-02-04 00:00 UTC, masonen commented on includes/webhook.sh
> +  if [ ${WEBHOOK_ENABLED:false} == "true" ]; then
make usage of webhooks more convienient - no mor need to check for the toogle before every call.

2024-02-08 14:11 UTC, jammsen commented
> ## Summary
> This PR introduces the possiblity to controll the gameserver status (start & stop the server) via a webhook

Do you mean ability? Possibilty sounds like, it works maybe 3 out of 30 calls 🤣 

> ## Motivation
> Currently the dedicated servers still face a bug where pals are loosing sanity or starve when no player is connected and they get stuck. A current workaround is to stop the server while no one is active. While this bug is of course not in scope of this project i still consider the changes valuable to the project.

They get stuck when you are online and not in render range or even in render range too, so no changes here.
What a current workaround is to stop the server? Why not turn of `bEnableNonLoginPenalty`? `While this bug is of course not in scope of this project i still consider the changes valuable to the project.` I dont get this, you say its a bug with the game, but still want me to fix it? Is that right?

> Since my servers are used by a small defined group of people which dont have direct CLI access to my host machines (and should not get it) an _incomming_ webhook is a good solution to allow them to controll the serverstatus.

So is a solution like Portainer, that way they can stop, start, resume. pause?

> Its not in the scope of this project how the webhook is accessed by the "outside world". 

Wait WHAT? You want me to add something that totally breaks the current server workflow AND ALSO everyone using it and dont want to offer a solution because its out of scope? What?! 😱 

> The hoster can decide on how to make this webhooks availiable to the users/admins of the servers. In my case im currently building a discord bot to access the webhooks securely inside my network without publicly exposing the webhooks, other usecases might include direct web access, web integrations and many more (up to the server maintainer.

This is in now way really helpful, nor new-user friendly is it? However is an adaptation, to your current problem i guess?


> Just stoping the server via RCON is ofcourse working but this will also terminate (and restart) the container if its set to "unless-stopped". If restart policy is set to "on-error" the container will keep stopped, but without access to the host one can not start it.

Again isnt Portainer a solution? A non-admin friendly way, to just stop it and start it again if needed?

> Other scenarios i was considering was a docker in docker setup where i will have the webhooks handle in a container thet spawn the server container. Was working fine but it might overwhelm people to set up on their own.

Docker in Docker with dedicated servers might be possible, but afaik it always comes with a heavy cost to responsetimes in ms. Would not recommend to do this.
 
> ## Changes included
> * rework of servermanager to handle the spawn of the webhook if envvar is set. Extract all other functionalities regarding server handling or termination handling to own script
> * introduction of remotestart and remote stop script which is used by the webhook
> * introduction of new webhook outputs related to the remote controll webhooks
> * introduce a build layer to the dockerfile that builds the webhook binary from source (https://github.com/adnanh/webhook)
> * small fixesin default.env (spaces only allowed inside quotes), fixes in envvars of docker file

Thanks for explaining the changes, but we have a very big PR that restructures the main repo, pretty sure, this would not be compatible.

I will look into the review of the files, however is still dont understand whats the reasoning for adding this would be? Because what i read is, you dont want to change something on your end? So i should do it on my end? Why? Whats in for all of the users to use this? Why start the server via api and some scripts? Why isnt supervisord here a better or lesser solution?

2024-02-08 14:19 UTC, jammsen requested changes

2024-02-08 14:19 UTC, jammsen commented on Dockerfile
> +    WEBHOOK_URL="" \
This introduces a bug with the SED scripts.

2024-02-08 14:19 UTC, jammsen commented on Dockerfile
> +RUN curl -L --silent -o webhook.tar.gz https://github.com/adnanh/webhook/archive/${WEBHOOK_VERSION}.tar.gz && \
This neither a good nor secure way to install software and doesnt follow the Ansible way.

2024-02-08 14:19 UTC, jammsen commented on Dockerfile
> +FROM golang:alpine AS build
Not going to happen in any of my images, even in multistage builds.

2024-02-08 14:19 UTC, jammsen commented on Dockerfile
> +    PUBLIC_IP="" \
here too

2024-02-08 14:19 UTC, jammsen commented on Dockerfile
> +    REGION="" \
here too

2024-02-08 14:19 UTC, jammsen commented on README_ENV.md
> +| REMOTE_CONTROL                  | If enabled server will not automatically start on container start and can be started/stopped via webhook call. Stop of the gameserver does not exit the container t
If enabled gameserver ...

2024-02-08 14:19 UTC, jammsen commented on README_ENV.md
> +If you enable the container setting the Container will not autostart the gameserver, it will however provide webhooks that allow you to control the server remotely. Hooks provided are
Which setting again? Im a new user, why isnt this desribed here, its a readme right?

2024-02-08 14:19 UTC, jammsen commented on default.env
> +BACKUP_CRON_EXPRESSION="0 * * * *"
Introduces a "" bug

2024-02-08 14:19 UTC, jammsen commented on default.env
> +SERVER_DESCRIPTION="Palworld-Dedicated-Server running in Docker by jammsen"
Introduces a bug ""

2024-02-09 11:13 UTC, masonen commented
Hey. Thanks for your comments so far. I'll give an detail answer once I'm back from vacation end of this month.

2024-02-14 13:06 UTC, M1XZG commented
Please excuse the drive-by comment, but what I do on my server is I use `autoheal` to ensure the container is running or restarted if the container stops.. 

I'll just paste my entire `docker-compose.yaml` file.. 

In the main `palworld-dedicated-server` service I've added a label that `autoheal` uses, then at the end of the yaml file you can see the `autoheal` configuration.

```
    labels:
      - "autoheal=true"
```

```
version: '3.3'
services:
  palworld-dedicated-server:
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    labels:
      - "autoheal=true"
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    env_file:
      - ./default.env
    volumes:
      - /docker-data/palworld:/palworld

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

You can run autoheal as a completely separate container on it's own but I just added it to my palworld config since it's the only container I currently use it with on this instance. 

Now if you use console/rcon to shutdown the server autoheal will automatically restart it, this makes it easier to restart the server on schedule or manually when needed.

2025-08-19 11:40 UTC, GlitchApotamus commented
That must've been a rough vacation. I'm assuming this PR could be voided out. @jammsen

2026-05-23 10:02 UTC, jammsen commented
Closed because of inactivity.

2026-05-23 10:02 UTC, closed without merging